server:
  port: 12345

logging:
  file:
    name: info.log
spring:
  web:
    locale: en_US
  config:
    # import your secret database configuration
    import:
      - classpath:application-database.yml
      - classpath:application-eh.yml
  mvc:
    static-path-pattern: /static/**
  task:
    execution:
      pool:
        core-size: 1
        max-size: 2