name: Build & Deploy

# Trigger on push to master branch or with a tag
on:
  push:
    branches:
      - '**'
    tags:
      - v*

# If previous workflow is still running, we push again, we will cancel the previous workflow
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  Build:
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      # Checkout branch
      - name: Checkout
        uses: actions/checkout@v3
      # Setup Database
      - name: Setup Database
        run: |
          echo "${{ secrets.DATABASE_CONFIG_FILE }}" > src/main/resources/application-database.yml
      # Setup JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: maven
      # Build
      - name: Build
        run: mvn package
      # Upload Artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JHenTai
          path: target/*.jar
  Deploy:
    #    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Make tmp dir
        run: mkdir /tmp/artifacts
      - name: Download jar
        uses: actions/download-artifact@v3
        with:
          path: /tmp/artifacts
      - name: List jar
        run: ls -R /tmp/artifacts
      - name: Upload jar
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: /tmp/artifacts/JHenTai/*.jar
          target: /usr/local/jhentai/JHenTai.jar
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SERVER_HOST}}
          port: ${{secrets.SERVER_PORT }}
          username: ${{secrets.SERVER_USERNAME}}
          key: ${{secrets.SERVER_PRIVATE_KEY}}
          script: |
            cd /usr/local/jhentai
            ls